security:

    encoders:
        LoginProject\Bundle\MainBundle\Entity\CurrentUser:
            algorithm: md5

    providers:
        db:
            entity:
                class: LoginProject\Bundle\MainBundle\Entity\CurrentUser
                property: username

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern:    ^/
            provider: db
            anonymous:  ~
            form_login:
                login_path: /user/login

    access_control:
        - { path: ^/user/(login|auth|register), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: ROLE_USER }
