LoginProject\Bundle\UserBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: LoginProject\Bundle\UserBundle\Repository\UserRepository
    uniqueConstraints:
        uk_username:
            columns:
                - username
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 64
            fixed: false
            comment: ''
        password:
            type: string
            nullable: false
            length: 32
            fixed: false
            comment: ''
        email:
            type: string
            nullable: false
            length: 128
            fixed: false
            comment: ''
        birthday:
            type: date
            nullable: false
            comment: ''
        isAdmin:
            type: integer
            nullable: false
            default: 0
            comment: ''
            column: is_admin
        ageStatus:
            type: string
            nullable: true
            length: null
            fixed: false
            comment: ''
            default: overage
            column: age_status
        createdAt:
            type: datetime
            nullable: false
            comment: ''
            default: CURRENT_TIMESTAMP
            column: created_at
